time:
  duration: 60.0 # [s]
  fsim: 50 # [Hz]
  year: 2023
  month: 12
  day: 14
  second: 18

constellations:
  mask_angle: 10.0 # [deg]
  emitters:
    gps:
      signal: gpsl1ca
      js: 0.0
      correlator_model: bpsk
    iridium-next:
      signal: freedom
      js: 0.0
      correlator_model: bpsk


