time:
  duration: 281.98 # [s]
  fsim: 50 # [Hz]
  year: 2024
  month: 1
  day: 31
  hour: 18
  minute: 19
  second: 18

constellations:
  mask_angle: 10.0 # [deg]
  emitters:
    gps:
      signal: gpsl1ca
      js: 5.0
    iridium-next:
      signal: freedom
      js: 0.0

errors:
  ionosphere: klobuchar
  troposphere: saastamoinen
  rx_clock: low_quality_tcxo

