type: measurement

time:
  duration: 3600.0 # [s]
  fsim: 1 # [Hz]
  year: 2023
  month: 10
  day: 14
  second: 18

constellations:
  mask_angle: 10.0 # [deg]
  emitters:
    gps:
      signal: gpsl1ca
      js: 0.0
    iridium-next:
      signal: freedom
      js: 0.0

errors:
  ionosphere: tec_map
  troposphere: saastamoinen
  rx_clock: low_quality_tcxo

